In [2]:
import nltk

We get preinstalled collections of data to work upon

Corpus - Large collection of data

In [7]:
#will download the datasets
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [8]:
from nltk.corpus import brown

In [11]:
# brown corpus has different categories of data...
print(brown.categories())
len(brown.categories())

['adventure', 'belles_lettres', 'editorial', 'fiction', 'government', 'hobbies', 'humor', 'learned', 'lore', 'mystery', 'news', 'religion', 'reviews', 'romance', 'science_fiction']


15

- Adventure is a class, these data are labelled
- we can make a topic based classifier which will tell us whether the sentence belongs to 'adventure','fiction','government'

In [14]:
data = brown.sents(categories='fiction')

In [17]:
print(data)

[['Thirty-three'], ['Scotty', 'did', 'not', 'go', 'back', 'to', 'school', '.'], ...]


- List of lists
- each list is a sentence

In [18]:
len(data)
#we have 4249 sentences

4249

In [20]:
print(data[3])

['His', 'teacher', 'and', 'his', 'school', 'principal', 'were', 'conferred', 'with', 'and', 'everyone', 'agreed', 'that', ',', 'if', 'he', 'kept', 'up', 'with', 'a', 'certain', 'amount', 'of', 'work', 'at', 'home', ',', 'there', 'was', 'little', 'danger', 'of', 'his', 'losing', 'a', 'term', '.']


- each sentence is broken into  a list of words

In [23]:
#see the data by joining with space
' '.join(data[4])

'Scotty accepted the decision with indifference and did not enter the arguments .'

# Bag of words pipeline

- Get the data/corpus
- Tokenisation, Stopward removal
- Stemming/Lemmatization
- Build a vocab
- Vectorisation
- Classification

## Tokenisation, Stopword Removal

In [24]:
document = """I hope you're pleased with yourselves. We could all have been killed — or worse, expelled.
                Now if you don't mind, I'm going to bed."""

sentence = "Send all the 50 documents related to chapters 1,2,3 at vineetchanana@gmail.com"

In [25]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [30]:
sents = sent_tokenize(document)

In [32]:
print(sents)
len(sents)

["I hope you're pleased with yourselves.", 'We could all have been killed — or worse, expelled.', "Now if you don't mind, I'm going to bed."]


3

In [36]:
#using split to break into words 
sentence.split()

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'vineetchanana@gmail.com']

- it didnot separate 1,2,3, if we want to split, pass the separater = ','

In [33]:
words = word_tokenize(sentence)

In [34]:
print(words)

['Send', 'all', 'the', '50', 'documents', 'related', 'to', 'chapters', '1,2,3', 'at', 'vineetchanana', '@', 'gmail.com']


it also break about the '@' special character

## Stopwords

- either we can use our own stopwords or import from nl toolit (it has some common stopwords)

In [37]:
from nltk.corpus import stopwords

In [43]:
#we want stopwords of language english

In [44]:
sw = set(stopwords.words('english'))

In [42]:
print(sw)

{'ours', 'only', 'ma', 'against', 'being', 'who', 'not', 'once', 'over', 'more', 'will', "haven't", 'than', "you're", 'same', 'down', 'from', 'been', "should've", 'out', 'your', 'but', 'doesn', 'mustn', 'my', 'don', "shouldn't", 'this', 'were', 'did', 'most', 'during', 'it', 'of', "you've", 'do', 'there', 'few', 's', 'how', "mustn't", 'isn', 'as', 'you', 'through', 'all', "couldn't", 'myself', 'the', 'yourselves', 'about', "wouldn't", "shan't", 'those', "isn't", 'until', 'under', 'itself', "won't", 'had', 'then', 'no', 'while', 'their', 'on', 'aren', 'they', "wasn't", "you'll", 'between', 'some', 'ourselves', 'be', 'having', 'very', 'now', "hasn't", 't', "mightn't", 'what', 'just', "that'll", 'me', 'doing', 'them', 'or', 'am', 'shan', "didn't", "she's", 'o', 'y', 'her', 'himself', 'into', 'll', 're', 'own', 'whom', 'mightn', 'ain', 'these', 'does', 'so', 'for', 'haven', 'at', 'theirs', 'after', 'won', 'she', 'wouldn', 'in', 'are', 'why', 'other', 'when', 'hadn', 'can', 'because', "don'

In [46]:
def remove_stopwords(text,stopwords):
    useful_words = [w for w in text if w not in stopwords]
    return useful_words

In [55]:
text = 'i am not bothered about her very much.'.split()

In [56]:
useful_words = remove_stopwords(text,sw)

In [57]:
useful_words

['bothered', 'much.']

- but it also removed the word 'not', it changed the context of sentence as it removed the negation
- if you want 'not' put a condition that word should not be 'not'

## Tokenisation using regular expressions

In [59]:
sentence = "Send all the 50 documents related to chapters 1,2,3 at vineetchanana@gmail.com"

In [60]:
sentence.split()

['Send',
 'all',
 'the',
 '50',
 'documents',
 'related',
 'to',
 'chapters',
 '1,2,3',
 'at',
 'vineetchanana@gmail.com']

- we are getting numbers, we donot want them as they are not meaningful
- we can't use stopwords or any harcoded logic to remove numbers as there are infinite numbers
- therefore we will use regular expressions to extract words

In [61]:
from nltk.tokenize import RegexpTokenizer

In [75]:
pattern = '[a-zA-Z]+'

In [76]:
tokenizer = RegexpTokenizer(pattern)

In [77]:
useful_text = tokenizer.tokenize(sentence)

In [82]:
print(useful_text)
len(useful_text)

['Send', 'all', 'the', 'documents', 'related', 'to', 'chapters', 'at', 'vineetchanana', 'gmail', 'com']


11

- we removed all the numbers

if you want to preserve gmail id, add '@' and '.' to regular expression

In [80]:
pattern2 = '[a-zA-Z@.]+'

In [83]:
tokenizer2 = RegexpTokenizer(pattern2)
usefultext2 = tokenizer2.tokenize(sentence)
print(usefultext2)
len(usefultext2)

['Send', 'all', 'the', 'documents', 'related', 'to', 'chapters', 'at', 'vineetchanana@gmail.com']


9

## Stemming 

- Process that transforms particular words(verbs,plurals) into their radical form
- Preserve the semantics of the sentence without increasing number of unique tokens (which will help in reducing number of unique features
- Example: jumps,jumping,jumped,jump => jump

In [84]:
# Snowball Stemmer,Porter , Lancaster Stemmer
from nltk.stem.snowball import SnowballStemmer,PorterStemmer
from nltk.stem.lancaster import LancasterStemmer

In [85]:
#make an object of this class
ps = PorterStemmer()

In [86]:
ps.stem('jumps')

'jump'

In [87]:
ps.stem('jumping')

'jump'

In [88]:
ps.stem('jumped')

'jump'

In [ ]:
#rules bne hue h like 'ing' hoga to remove kr denge 

In [89]:
#Snowball is a multi-lingual stemmer(Can also stem french, german words)
ss = SnowballStemmer('english')  # as it is a multi-lingual need to mention the language

In [90]:
ss.stem('loves')

'love'

In [91]:
ss.stem('lovely')

'love'

In [92]:
# this will also produce the very similar results
from nltk.stem.wordnet import WordNetLemmatizer

In [ ]:
wn = WordNetLemmatizer()
wn.lemmatize('jumps')
#need to install this 

## Building  a Vocab and Vecorization

In [94]:
corpus = [
    "I’m selfish, impatient and a little insecure. I make mistakes, I am out of control and at times hard to handle. But if you can’t handle me at my worst, then you sure as hell don’t deserve me at my best.",
    "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
    "I can’t give you a sure-fire formula for success, but I can give you a formula for failure: try to please everybody all the time.",
    "It is hard to fail, but it is worse never to have tried to succeed."
]

- This corpus have 4 documents, we will make a feature vector for each document so that we can classify the documents
- if a word will come twice we will put 2 at that index
- feature vector will be able to tell us that what words came in the document and how many times they came

In [4]:
from sklearn.feature_extraction.text import CountVectorizer

In [104]:
#make an object
cv = CountVectorizer()
vectorized_corpus = cv.fit_transform(corpus)
# fit will learn the dictionary(vocab) from the corpus and tranform will convert the data into numbers

In [105]:
#sparse matrix
vectorized_corpus

<4x62 sparse matrix of type '<class 'numpy.int64'>'
	with 75 stored elements in Compressed Sparse Row format>

In [118]:
len(vectorized_corpus[0])

62

In [106]:
#cobvert sparse matrix to array
vectorized_corpus = vectorized_corpus.toarray()
print(vectorized_corpus)

[[0 1 2 1 3 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 2 1 0 1 0 1 1 1 0 0 0 1 1 0 2
  1 2 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0 1 1 0 0 0 0 0 1 2]
 [0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 0 1 0
  0 0 0 0 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0]
 [1 0 0 0 0 0 0 1 2 0 0 0 1 0 1 1 0 2 2 0 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 1 0 1 1 0 0 1 0 1 0 1 0 0 0 0 2]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 2 2 0 0 0 0 0
  0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 3 1 0 0 0 1 0 0]]


In [107]:
print(len(vectorized_corpus))
# we can see we have 4 feature vectors (docs)

4


In [110]:
vectorized_corpus[2]

array([1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 1, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2], dtype=int64)

- if you want to find out how mapping is done
- cv has a attribute 'vocabulary' that got learned during fit method, will tell us the mapping of the word and the index

In [112]:
print(cv.vocabulary_)

{'selfish': 44, 'impatient': 27, 'and': 2, 'little': 32, 'insecure': 28, 'make': 33, 'mistakes': 36, 'am': 1, 'out': 42, 'of': 39, 'control': 9, 'at': 4, 'times': 53, 'hard': 22, 'to': 54, 'handle': 21, 'but': 7, 'if': 26, 'you': 61, 'can': 8, 'me': 35, 'my': 37, 'worst': 60, 'then': 50, 'sure': 48, 'as': 3, 'hell': 24, 'don': 11, 'deserve': 10, 'best': 5, 'successful': 47, 'man': 34, 'is': 29, 'one': 40, 'who': 57, 'lay': 31, 'firm': 16, 'foundation': 19, 'with': 58, 'the': 49, 'bricks': 6, 'others': 41, 'have': 23, 'thrown': 51, 'him': 25, 'give': 20, 'fire': 15, 'formula': 18, 'for': 17, 'success': 46, 'failure': 14, 'try': 56, 'please': 43, 'everybody': 12, 'all': 0, 'time': 52, 'it': 30, 'fail': 13, 'worse': 59, 'never': 38, 'tried': 55, 'succeed': 45}


In [113]:
len(cv.vocabulary_)

62

In [114]:
len(vectorized_corpus[2])

62

- we can see the length of the feature vector is equal to the length of the vocaabulary

### Reverse mapping
- if you want to convert data from numbers to text
- given a list of numbers, how to find a sentence

In [115]:
numbers = vectorized_corpus[2]
numbers

array([1, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 1, 0, 2, 2, 0, 2, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 2], dtype=int64)

In [116]:
cv.inverse_transform(numbers)

[array(['all', 'but', 'can', 'everybody', 'failure', 'fire', 'for',
        'formula', 'give', 'please', 'success', 'sure', 'the', 'time',
        'to', 'try', 'you'], dtype='<U10')]

- we can see the words are shuffled, that's why it is a bag of words model

## Vectorization with Stopword removal

In [121]:
corpus.lower()

AttributeError: 'list' object has no attribute 'lower'

In [122]:
def myTokenizer(document):
    # this tokenizer is our custom regular expressions based tokenizer
    words = tokenizer.tokenize(document.lower())
    # lower the words so that Indian and indian means the same
    
    #remove stopwords
    words = remove_stopwords(words,sw)
    return words

In [124]:
print(sentence)
myTokenizer(sentence)

Send all the 50 documents related to chapters 1,2,3 at vineetchanana@gmail.com


['send', 'documents', 'related', 'chapters', 'vineetchanana', 'gmail', 'com']

In [127]:
#we can pass our own tokenizer
cv2 = CountVectorizer(tokenizer=myTokenizer)

In [136]:
vectorized_corpus2 = cv2.fit_transform(corpus).toarray()

In [137]:
vectorized_corpus2

array([[1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
        0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 0, 2, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0]], dtype=int64)

In [138]:
print(len(vectorized_corpus[0]))
len(vectorized_corpus[1])

62


62

- By using our own tokenizer we reduced the length of the vector...makes our data represntable,memory friendly, reduces the dimensions, makes our data meaningful. 
- it is preferable to have bcoz if we have 1 lakh words, our performance will degrade because we are not doing stemming, clubbing similar words together then it will be difficult to generalise over new data

In [140]:
cv2.inverse_transform(vectorized_corpus2)

[array(['best', 'control', 'deserve', 'handle', 'hard', 'hell',
        'impatient', 'insecure', 'little', 'make', 'mistakes', 'selfish',
        'sure', 'times', 'worst'], dtype='<U10'),
 array(['bricks', 'firm', 'foundation', 'lay', 'man', 'one', 'others',
        'successful', 'thrown'], dtype='<U10'),
 array(['everybody', 'failure', 'fire', 'formula', 'give', 'please',
        'success', 'sure', 'time', 'try'], dtype='<U10'),
 array(['fail', 'hard', 'never', 'succeed', 'tried', 'worse'], dtype='<U10')]

#### for test data
- we will have the same dictionary of training data, we will not learn new vocab for test data we will only use vocab that was learned during training data

In [141]:
test_corpus = [
    "impatient and a little insecure."
]

- in this case would you expect our vocab to have only 4 words, in ML both training and test data should have similar representation. We can not shrink the vocabulary
- that's why we will only transform the data and not fit(learn new parameters for data)
- donot use fit_transform as it will override our dictionary

In [143]:
cv2.transform(test_corpus).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

## More ways to create features
- Unigram - using every word as a feature
- Bigram - using 2 consecutive words as a feature
- Trigram - using 3 consecutive words as a feature
- n-gram - Combine all the unigram,bigram,trigram

In [1]:
sent_1 = ['this is good movie']
sent_2 = ['this is good movie but actor is not present']
sent_3 = ['this is not good movie']

If we use unigram features for the classifier it might possible that classifier predicts that 3rd sentence is a positive review because in first two reviews 'good' and 'movie' both words are present and they are both +ve reviews, so it might predict 3rd as +ve too, it's difficult to catch negation...

In [3]:
docs= [sent_1[0],sent_2[0],sent_3[0]]

In [5]:
cv = CountVectorizer(ngram_range=(1,1))

In [7]:
cv.fit_transform(docs).toarray()

array([[0, 0, 1, 1, 1, 0, 0, 1],
       [1, 1, 1, 2, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 0, 1]], dtype=int64)

In [9]:
print(cv.vocabulary_)

{'this': 7, 'is': 3, 'good': 2, 'movie': 4, 'but': 1, 'actor': 0, 'not': 5, 'present': 6}


In [19]:
##bigram
cv2 = CountVectorizer(ngram_range=(2,2))
cv2.fit_transform(docs)
print(cv2.vocabulary_)
print('\nLength of vocabulary:', len(cv2.vocabulary_))

{'this is': 8, 'is good': 3, 'good movie': 2, 'movie but': 5, 'but actor': 1, 'actor is': 0, 'is not': 4, 'not present': 7, 'not good': 6}

Length of vocabulary: 9


- we are getting 'is good' and 'not good' both...we are capturing negation

In [18]:
##trigram
cv3 = CountVectorizer(ngram_range=(3,3))
cv3.fit_transform(docs)
print(cv3.vocabulary_)
print('\nLength of vocabulary:', len(cv3.vocabulary_))

{'this is good': 8, 'is good movie': 3, 'good movie but': 2, 'movie but actor': 6, 'but actor is': 1, 'actor is not': 0, 'is not present': 5, 'this is not': 9, 'is not good': 4, 'not good movie': 7}

Length of vocabulary: 10


In [17]:
##ngram -combining all the features
cv4 = CountVectorizer(ngram_range=(1,3))
cv4.fit_transform(docs)
print(cv4.vocabulary_)
print('\nLength of vocabulary:', len(cv4.vocabulary_))

{'this': 23, 'is': 9, 'good': 6, 'movie': 15, 'this is': 24, 'is good': 10, 'good movie': 7, 'this is good': 25, 'is good movie': 11, 'but': 3, 'actor': 0, 'not': 18, 'present': 22, 'movie but': 16, 'but actor': 4, 'actor is': 1, 'is not': 12, 'not present': 21, 'good movie but': 8, 'movie but actor': 17, 'but actor is': 5, 'actor is not': 2, 'is not present': 14, 'not good': 19, 'this is not': 26, 'is not good': 13, 'not good movie': 20}

Length of vocabulary: 27


- Length of vocabulary is getting increased...we have to keep a check on the memory

## Tf-idf Normalisation

- avoids features that occur very often, because they contain less information
- information decreases as the number of occurences inccreases across all the documents
- So we define another term term-document-frequency which associates a weight with every word

In [22]:
sent_1 = "this is good movie"
sent_2 = "this was good movie"
sent_3 = "this is not good movie"

corpus = [sent_1,sent_2,sent_3]

In [23]:
corpus

['this is good movie', 'this was good movie', 'this is not good movie']

In [24]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [25]:
#make an object
tfidf = TfidfVectorizer()

In [28]:
vc = tfidf.fit_transform(corpus).toarray()

In [29]:
print(vc)

[[0.46333427 0.59662724 0.46333427 0.         0.46333427 0.        ]
 [0.41285857 0.         0.41285857 0.         0.41285857 0.69903033]
 [0.3645444  0.46941728 0.3645444  0.61722732 0.3645444  0.        ]]


In [30]:
tfidf.vocabulary_

{'this': 4, 'is': 1, 'good': 0, 'movie': 2, 'was': 5, 'not': 3}

In [35]:
tfidf.inverse_transform(vc[2])[0][3]

'not'

- we can see 'not' has maximum weight in 2nd doc because other words are also occuring other documents
- in 1st doc, 'was' has higher weight