In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
print(x)
print(x+4)

[1 2 3 4]
[5 6 7 8]


In [7]:
X = np.array([[10,40],[20,50],[30,60],[40,70]])
Y = np.array([[10, 20, 30, 40],[50,60,70,80]])
print(Y)
print(Y+x)
# element of x got broadcasted to another row
#1 2 3 4    10 20 30 40
#1 2 3 4    50 60 70 80

[[10 20 30 40]
 [50 60 70 80]]
[[11 22 33 44]
 [51 62 73 84]]


In [10]:
#Element-wise Multiplication
#dimension of matrix should be same
A = np.random.randint(1,10,(2,2))
B = np.random.randint(1,10,(2,2))
print(A)
print(B)

[[5 2]
 [8 6]]
[[1 7]
 [9 8]]


In [11]:
print(A*B)

[[ 5 14]
 [72 48]]


In [13]:
#Matrix Multiplication
print(A.dot(B))
print(np.dot(A,B))

[[ 23  51]
 [ 62 104]]
[[ 23  51]
 [ 62 104]]


## Norms

- Norms can be thought of a proxy for size of a vector   (can think of as a magnitude of a vector)
    - 3i + 2j , L^2 = sqrt(3^2 + 2^2)
    - f(x) => x=0
    - f(x+y) < f(x) + f(y)
    - f(alpha*x) = alpha * f(x)
    
- $L{^2}$ is also kwown as Eucledian Norm, often ||x||
- $L{^2}$ is also equal to $x{^T}$x
- $L{^2}$, deriavtive is 2*x (as it is similar to $x{^2}$)

- $L{^1}$ norm is absolute sum of all values of a vector
-  Max-Norm -  $L{^\infty}$ is absolute value of the element with the highest magnitude

In [17]:
a = np.array([3,4])

#by default it gives lp2 norm
lp2 = np.linalg.norm(a)
print(lp2)

lp1 = np.linalg.norm(a,ord=1)
print(lp1)

lpinf = np.linalg.norm(a,ord=np.inf)
print(lpinf)

5.0
7.0
4.0


## Determinants

In [21]:
X = np.array([[1,2],[3,4]])
print(X)
det = np.linalg.det(X)
print(det)

[[1 2]
 [3 4]]
-2.0000000000000004


## Inverse

In [19]:
A = np.array([[3,2],[4,1]])
print(A)
inv = np.linalg.inv(A)
print(inv)

[[3 2]
 [4 1]]
[[-0.2  0.4]
 [ 0.8 -0.6]]


In [30]:
# A*Ainv gives identity matrix
print(A.dot(inv))

[[1.00000000e+00 2.22044605e-16]
 [0.00000000e+00 1.00000000e+00]]


## Pseudoinverse
- when det is zero, we calculate pseudo inverse
- if matrix is invertible (det is not equal to zero), pinv = inv

In [32]:
print(np.linalg.inv(A))
print(np.linalg.pinv(A))

[[-0.2  0.4]
 [ 0.8 -0.6]]
[[-0.2  0.4]
 [ 0.8 -0.6]]


In [37]:
B = np.array([[2,3],[2,3]])
print(B)
#print(np.linalg.inv(B))  will give error
print(np.linalg.pinv(B))

[[2 3]
 [2 3]]
[[0.07692308 0.07692308]
 [0.11538462 0.11538462]]


## Solve a system of equations

3x + 2y = 8
4x + 5y = 18

[[3,2], [4,5]] = [[8],[18]]

In [45]:
a = np.array([[2,3],[3,1]])
b = np.array([8,5])
print(a)
print(b)

[[2 3]
 [3 1]]
[8 5]


In [46]:
np.linalg.solve(a,b)

array([1., 2.])