In [3]:
import numpy as np

Compute the infinite norm of the following matrix

2	-2	1

-1	2	-1

2	-4	1


In [4]:
a = np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])
print(a)

[[ 2 -2  1]
 [-1  2 -1]
 [ 2 -4  1]]


In [6]:
#i guess first row gives 5, 2nd-> 4 and 3rd gives 7
lpinf = np.linalg.norm(a,ord=np.inf)
lpinf

7.0

The L2 norm is also called as Frobenius norm. Compute the Frobenius norm of the following matrix

2	-2	1

-1	2	-1

2	-4	1

In [8]:
#calculate norm of each row then calculate combined values of norm of each rows
lp2 = np.linalg.norm(a)
lp2

6.0

Q3. Matrix Multiplication
Let A matrix be

1	-3	4

-2	10	-7

0	1	0

0	0	0

Let B matrix be

5	0

-2	11

-3	12

Which of the following matrices is equal to the matrix AB ?

In [11]:
A = np.array([[1,-3,4],[-2,10,-7],[0, 1, 0],[0, 0, 0 ]])
B = np.array([[5, 0 ],[-2, 11],[-3, 12]])
print(A)
print(B)
print()
print(A.dot(B))

[[ 1 -3  4]
 [-2 10 -7]
 [ 0  1  0]
 [ 0  0  0]]
[[ 5  0]
 [-2 11]
 [-3 12]]

[[-1 15]
 [-9 26]
 [-2 11]
 [ 0  0]]
