In [1]:
import pandas as pd
import numpy as np

In [8]:
X = np.random.randint(1,100,(1,6))
Y = np.random.randint(1,100,(1,6))
Z = np.random.randint(1,100,(1,6))

print(X,Y,Z)

[[87 48 78 90 22 28]] [[62 52 48  6 22 84]] [[82 55 71 52 43 48]]


In [10]:
user_data = {
    'MarksA' : np.random.randint(1,100,5),
    'MarksB' : np.random.randint(1,100,5),
    'MarksC' : np.random.randint(1,100,5)
}

print(user_data)

{'MarksA': array([15, 70, 62, 88, 67]), 'MarksB': array([58, 21, 84, 55, 66]), 'MarksC': array([86, 87, 19, 58, 86])}


In [12]:
df = pd.DataFrame(user_data)

df.head()

MarksA  MarksB  MarksC
0      15      58      86
1      70      21      87
2      62      84      19
3      88      55      58
4      67      66      86

In [13]:
#To select a row
df.iloc[3]

MarksA    88
MarksB    55
MarksC    58
Name: 3, dtype: int32

In [14]:
#a row and a column
df.iloc[3,1]

55

In [15]:
df.iloc[:3,1]

0    58
1    21
2    84
Name: MarksB, dtype: int32

In [20]:
#if we donot now the index of column
idx = df.columns.get_loc('MarksB')
df.iloc[:3,idx]
#print(idx)

0    58
1    21
2    84
Name: MarksB, dtype: int32

In [28]:
idx = [df.columns.get_loc('MarksB'),df.columns.get_loc('MarksC')]

print(idx)
df.iloc[3,idx]

[1, 2]


MarksB    55
MarksC    58
Name: 3, dtype: int32

In [29]:
#sort values
df.sort_values(by=['MarksA'],ascending=False)

MarksA  MarksB  MarksC
3      88      55      58
1      70      21      87
4      67      66      86
2      62      84      19
0      15      58      86

In [30]:
#will get sorted by C
df.sort_values(by=['MarksC','MarksA'],ascending=False)

MarksA  MarksB  MarksC
1      70      21      87
4      67      66      86
0      15      58      86
3      88      55      58
2      62      84      19

In [32]:
data_array = df.values
print(data_array)

[[15 58 86]
 [70 21 87]
 [62 84 19]
 [88 55 58]
 [67 66 86]]


In [36]:
new_df = pd.DataFrame(data_array,dtype='float32',columns=['Physics','Chemistry','Maths'])

In [37]:
new_df.head()

Physics  Chemistry  Maths
0     15.0       58.0   86.0
1     70.0       21.0   87.0
2     62.0       84.0   19.0
3     88.0       55.0   58.0
4     67.0       66.0   86.0