In [3]:
import numpy as np

In [2]:
a = np.arange(1,6)
print(a)
print(a.shape)

[1 2 3 4 5]
(5,)


In [4]:
b = np.arange(1,6).reshape(5,1)
print(b)
print(b.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


As 'a' is a 1d array and 'b' is a 2d array therofere there is a difference in shapes of the array

In [6]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [8]:
#element wise multiplication
print(a*b)
print(np.multiply(a,b))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [10]:
#dot product/matrix multiplication
print(a.dot(b))
print(np.dot(a,b))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [14]:
#multiplication of 2 vectors give a scalar
x = np.arange(1,5)
y = np.arange(1,5)
print(x)
print(y)

np.dot(x,y)

[1 2 3 4]
[1 2 3 4]


30

In [15]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [16]:
sum(a)

array([4, 6])

In [17]:
np.sum(a)

10

In [18]:
#it will sum along row
np.sum(a,axis=1)

array([3, 7])

In [19]:
#it will sum along column
np.sum(a,axis=0)

array([4, 6])

In [21]:
#stacking
y = y+4
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [27]:
z = np.stack((x,y),axis=0)
print(z)
print(z.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [28]:
z = np.stack((x,y),axis=1)
print(z)
print(z.shape)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]
(4, 2)


In [29]:
z = z.reshape(2,4)
print(z)
print(z.shape)

[[1 5 2 6]
 [3 7 4 8]]
(2, 4)


In [30]:
z = z.reshape(8,1)
print(z)
print(z.shape)

[[1]
 [5]
 [2]
 [6]
 [3]
 [7]
 [4]
 [8]]
(8, 1)


In [31]:
#if you want a linear array
z = z.reshape(8,)
print(z)
print(z.shape)

[1 5 2 6 3 7 4 8]
(8,)


In [34]:
#if you don't know 1 parameter and only knows row or column use -1
z = z.reshape(2,-1)
print(z)
print(z.shape)

w = z.reshape(-1,8)
print(w)
print(w.shape)

[[1 5 2 6]
 [3 7 4 8]]
(2, 4)
[[1 5 2 6 3 7 4 8]]
(1, 8)


## Random Generators Numpy

In [5]:
a = np.random.rand(2,3)
a

array([[0.78687165, 0.19997541, 0.83805054],
       [0.46414966, 0.92502418, 0.01181183]])

In [7]:
#random numbers from normal/standard distribution
b = np.random.randn(3,2)
b

array([[-1.56289047,  0.83559543],
       [ 1.3113428 ,  0.08303134],
       [-0.28654714, -2.66352077]])

In [19]:
c = np.random.randint(5,10,4)
c

array([8, 7, 6, 6])

In [23]:
#to shuffle an array
np.random.shuffle(c)
c

array([8, 7, 6, 6])

In [25]:
#to picka random number from  an array
element = np.random.choice([3,5,6,77])
element

5

In [33]:
#if you want to keep the random numbers fixed, seed stores the state..as these are pseudo generators they generate in a order
np.random.seed(14)
x = np.random.randint(2,8,4)
x

array([5, 2, 6, 3])

## Staistical Computation using NumPy

In [34]:
a = np.array([[1,3,2,4],[3,7,6,0]])
print(a)

[[1 3 2 4]
 [3 7 6 0]]


In [35]:
np.min(a)

0

- axis = 0 means we work on the columns,rows will change
- axis = 1 means we work on the rows,cols will change

In [37]:
np.min(a,axis=0)

array([1, 3, 2, 0])

In [38]:
np.min(a,axis=1)

array([1, 0])

In [41]:
#mean
c = np.array([1,2,3,4,5])

m = sum(c)/len(c)
print(m)

print(np.mean(c))

3.0
3.0


In [46]:
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

[2. 5. 4. 2.]
[2.5 4. ]


In [47]:
#median (middle most value)
d = np.array([1,4,5,2,0])
print(np.median(d))

2.0


Mean vs average
- In Average, we multiply each numbers with its weights
- n[i]*w[i]/len

In [52]:
w = np.array([1,2,3,4,5])
ones = np.ones(5)
print(np.mean(d))
print(np.average(d))
print(np.average(d,weights=ones))
print(np.average(d,weights=w))

2.4
2.4
2.4
2.1333333333333333


In [57]:
#standard deviation and variance
u = np.mean(d)
myStd = np.sqrt(np.mean(abs(d-u)**2))
print(myStd)
print(np.std(d))

1.854723699099141
1.854723699099141


In [60]:
#variance
print(myStd**2)
print(np.var(d))

3.440000000000001
3.4400000000000004
