In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,(3,3))
arr

array([[13,  2,  4],
       [ 6,  5,  4],
       [10, 18, 19]])

In [3]:
np.ravel(arr)

array([13,  2,  4,  6,  5,  4, 10, 18, 19])

In [4]:
np.ravel(arr,order='C')

array([13,  2,  4,  6,  5,  4, 10, 18, 19])

In [5]:
np.ravel(arr,order='F')

array([13,  6, 10,  2,  5, 18,  4,  4, 19])

In [6]:
np.ravel(arr,order='A')

array([13,  2,  4,  6,  5,  4, 10, 18, 19])

In [7]:
np.ravel(arr,order='K')

array([13,  2,  4,  6,  5,  4, 10, 18, 19])

In [10]:
np.Flatten?

Object `np.Flatten` not found.


In [12]:
arr.flatten()

array([13,  2,  4,  6,  5,  4, 10, 18, 19])

2 - Which of the following function stacks 1D arrays as columns into a 2D array?



In [14]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [15]:
b = np.arange(5) +5
b

array([5, 6, 7, 8, 9])

In [18]:
c = np.row_stack((a,b))
print(c)
c.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]


(2, 5)

In [22]:
d = np.column_stack((a,b))
print(d)
d.shape

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


(5, 2)

In [21]:
np.col_stack?

Object `np.col_stack` not found.


https://stackoverflow.com/questions/41518351/what-is-the-difference-between-resize-and-reshape-when-using-arrays-in-numpy

In [34]:
a = np.arange(10)
print(a)
t = np.reshape(a,(2,5))
#print(t)
#print(a)

a[0] = 999
print(a)
print(t)

[0 1 2 3 4 5 6 7 8 9]
[999   1   2   3   4   5   6   7   8   9]
[[999   1   2   3   4]
 [  5   6   7   8   9]]


In [36]:
print(a)
t = np.resize(a,(5,2))
#print(t)
#print(a)

a[0] = 30
print(a)
print(t)

[999   1   2   3   4   5   6   7   8   9]
[30  1  2  3  4  5  6  7  8  9]
[[999   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]]


In [28]:
np.reshape2?

Object `np.reshape2` not found.


In [32]:
np.resize(a,(5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [33]:
np.reshape(a,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Which of the following method gives you an array with the same content.

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr.copy()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr.view()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
arr.copyto()

AttributeError: 'numpy.ndarray' object has no attribute 'copyto'

Which of the following statement can convert a 2D numpy array to corresponding elements as list.
a = np.arange(0,9).reshape(3,3)

In [44]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [45]:
list(a)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [46]:
type(list(a))

list

In [48]:
print(a.tolist())
print(type(a.tolist()))

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
<class 'list'>


In [49]:
print(np.tolist(a))
print(type(np.tolist(a)))

AttributeError: module 'numpy' has no attribute 'tolist'

In [51]:
a.size

9

Get all the elements from a that are between 5 - 10.
a = np.random.randint(0,15, size=(4,4))

In [52]:

a = np.random.randint(0,15, size=(4,4))
a

array([[ 1,  3,  2,  2],
       [11,  6, 14, 13],
       [12,  2,  7,  3],
       [11, 11,  7,  4]])

In [55]:
c = np.where((a>=5) & (a<=10))
print(c)
a[c]


(array([1, 2, 3], dtype=int64), array([1, 2, 2], dtype=int64))


array([6, 7, 7])

In [57]:
a[(a>=5) & (a<=10)]

array([6, 7, 7])

In [58]:
a[np.all((a>=5) & (a<=10))]

array([], shape=(0, 4, 4), dtype=int32)

In [59]:
a

array([[ 1,  3,  2,  2],
       [11,  6, 14, 13],
       [12,  2,  7,  3],
       [11, 11,  7,  4]])

How can you swap the first and third channel of the array of shape (3,3,3)
img = np.arange(3*3*3).reshape(3,3,3)

In [60]:
img = np.arange(3*3*3).reshape(3,3,3)

In [61]:
img

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [62]:
img[::-1]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [65]:
print(img)
img[[2,1,0],:,:]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]]])

In [69]:
img[[2,1]]

array([[[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [67]:
print(img)
img[:, ::-1]

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[[ 6,  7,  8],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[15, 16, 17],
        [12, 13, 14],
        [ 9, 10, 11]],

       [[24, 25, 26],
        [21, 22, 23],
        [18, 19, 20]]])